# permissions for end users to view secretmanglers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretmangler-viewer-role
rules:
- apiGroups:
  - secret-mangler.wreiner.at.secret-mangler.wreiner.at
  resources:
  - secretmanglers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secret-mangler.wreiner.at.secret-mangler.wreiner.at
  resources:
  - secretmanglers/status
  verbs:
  - get
