# permissions for end users to edit secretmanglers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secretmangler-editor-role
rules:
- apiGroups:
  - secret-mangler.wreiner.at
  resources:
  - secretmanglers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secret-mangler.wreiner.at
  resources:
  - secretmanglers/status
  verbs:
  - get
