apiVersion: secret-mangler.wreiner.at/v1alpha1
kind: SecretMangler
metadata:
  name: <name>
  namespace: <namespace>
spec:
  secretTemplate:
    apiVersion: v1
    kind: Secret
    namespace: secret-namespace
    name: "secret-name"
    cascadeMode: [KeepNoAction|KeepLostSync|RemoveLostSync|CascadeDelete]
    mappings:
      fixedmapping: "some-value-which-will-used-as-is"
      dynamicmapping: "[NAMESPACE/]OBJECT_NAME:LOOKUP_FIELD"
