apiVersion: secret-mangler.wreiner.at.secret-mangler.wreiner.at/v1alpha1
kind: SecretMangler
metadata:
  name: mangler01
  namespace: aha
spec:
  secretTemplate:
    apiVersion: v1
    kind: Secret
    namespace: aha
    name: "mangler01-secret"
    cascadeMode: "KeepLostSync"
    mappings:
      fixedmapping: "fixedmapping-val"
      dynamicmapping: "<aha/mangler-secret:test>"
